[project]
name = "reconoscope"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dnspython[async]>=2.7.0",
    "fastapi[all]>=0.116.1",
    "loguru>=0.7.3",
    "phonenumbers>=9.0.13",
]
